<?php

namespace Blog\BlogOrnoirBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends EntityRepository
{
    public function getServicesByNouveaute() 
    {
        return $this->getEntityManager()
                ->createQuery('SELECT c FROM BlogOrnoirBundle:Services c ORDER BY c.id DESC')
                ->setMaxResults(6)
                ->getResult();
    }
    
    public function recherche($chaine) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.description like :chaine')
                ->setParameter('chaine', '%'.$chaine.'%')
                ->orderBy('u.id', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
