parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: kountacffauser3
    database_user: kountacffauser3
    database_password: 7DeuV2jC5T3AAt5@O
    mailer_transport: mail
    mailer_host: mx1.mail.ovh.net
    mailer_user: contact@kountac.fr
    mailer_password: kountac2018
    secret: ThisTokenIsNotSoSecretChangeIt
