<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EditeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditeursRepository extends EntityRepository
{
}
