<?php

namespace Blog\BlogOrnoirBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function getArticlesByNouveaute() 
    {
        return $this->getEntityManager()
                ->createQuery('SELECT c FROM BlogOrnoirBundle:Blog c ORDER BY c.id DESC')
                ->setMaxResults(6)
                ->getResult();
    }
    
    public function getArticlesByPopularite() 
    {
        return $this->getEntityManager()
                ->createQuery('SELECT c FROM BlogOrnoirBundle:Blog c ORDER BY c.popularite DESC')
                ->setMaxResults(5)
                ->getResult();
    }
    
    public function recherche($chaine) 
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.description like :chaine')
                ->setParameter('chaine', '%'.$chaine.'%')
                ->orderBy('u.id', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
