<?php

namespace Blog\BlogOrnoirBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCommentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentairesRepository extends EntityRepository
{
    public function getCommentairesByNouveaute() 
    {
        return $this->getEntityManager()
                ->createQuery('SELECT c FROM BlogOrnoirBundle:BlogCommentaires c ORDER BY c.id DESC')
                ->setMaxResults(5)
                ->getResult();
    }
}
