produit_pro_index:
    path:     /
    defaults: { _controller: "UtilisateursBundle:ProduitPro:index" }
    methods:  GET
    
produit_pro_new_1:
    path:     /new_1
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new1" }
    methods:  [GET, POST]
    
produit_pro_new_2:
    path:     /new_2_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new2" }
    methods:  [GET, POST]
    
produit_pro_new_motif:
    path:     /new_motif_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:addMotif" }
    methods:  [GET, POST]
    
produit_pro_new_3:
    path:     /new_3_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new3" }
    methods:  [GET, POST]

produit_pro_new_resume:
    path:     /new_resume_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:newResume" }
    methods:  [GET, POST]

produit_pro_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateursBundle:ProduitPro:show" }
    methods:  [GET, POST]

produit_pro_edit_1:
    path:     /{id}/edit_1
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_1" }
    methods:  [GET, POST]
    
produit_pro_edit_2:
    path:     /{id}/edit_2
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_2" }
    methods:  [GET, POST]
    
produit_pro_edit_21:
    path:     /{id}/edit_21
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_21" }
    methods:  [GET, POST]
    
produit_pro_edit_3:
    path:     /{id}/edit_3
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_3" }
    methods:  [GET, POST]
    
produit_pro_edit_31:
    path:     /{id}/edit_31
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_31" }
    methods:  [GET, POST]
    
produit_pro_edit_pays:
    path:     /{id}/edit_pays
    defaults: { _controller: "UtilisateursBundle:ProduitPro:editPays" }
    methods:  [GET, POST]

produit_pro_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateursBundle:ProduitPro:delete" }
    
produit_pro_stock_epuise:
    path:     /stock_épuisé
    defaults: { _controller: "UtilisateursBundle:ProduitPro:stock" }
    methods:  GET
    
produit_pro_sale:
    path:     /product_sales
    defaults: { _controller: "UtilisateursBundle:ProduitPro:sale" }
    methods:  GET
    
produit_pro_add_stock:
    path:     /{id}/add_stock
    defaults: { _controller: "UtilisateursBundle:ProduitPro:addStock" }
    methods:  [GET, POST]
    
produit_pro_add_prix_commande_cfa:
    path:     /{id}/add_prix_commande_cfa
    defaults: { _controller: "UtilisateursBundle:ProduitPro:addprixCommandeCfa" }
    methods:  [GET, POST]